-- Add cancelledBy column to appointment_requests
ALTER TABLE `appointment_requests` ADD COLUMN `cancelledBy` VARCHAR(20) NULL;

-- Update audit_logs enum to include new actions
ALTER TABLE `audit_logs` MODIFY COLUMN `action` VARCHAR(191) NOT NULL;

UPDATE `audit_logs` 
SET `action` = 'SMS_SENT' 
WHERE `action` NOT IN (
  'UI_PHONE_ENTERED',
  'UI_NAME_ENTERED',
  'UI_CANCEL_ATTEMPT',
  'APPOINTMENT_CREATED',
  'APPOINTMENT_APPROVED',
  'APPOINTMENT_CANCELLED',
  'APPOINTMENT_CANCEL_ATTEMPT',
  'APPOINTMENT_CANCEL_BLOCKED_PAST',
  'APPOINTMENT_CANCEL_BLOCKED_2H',
  'CUSTOMER_CANCEL_PHONE_ENTERED',
  'CUSTOMER_CANCEL_OTP_SENT',
  'CUSTOMER_CANCEL_CONFIRMED',
  'CUSTOMER_CANCEL_FAILED',
  'SMS_SENT',
  'SMS_FAILED'
);

ALTER TABLE `audit_logs` 
MODIFY COLUMN `action` ENUM(
  'UI_PHONE_ENTERED',
  'UI_NAME_ENTERED',
  'UI_CANCEL_ATTEMPT',
  'APPOINTMENT_CREATED',
  'APPOINTMENT_APPROVED',
  'APPOINTMENT_CANCELLED',
  'APPOINTMENT_CANCEL_ATTEMPT',
  'APPOINTMENT_CANCEL_BLOCKED_PAST',
  'APPOINTMENT_CANCEL_BLOCKED_2H',
  'CUSTOMER_CANCEL_PHONE_ENTERED',
  'CUSTOMER_CANCEL_OTP_SENT',
  'CUSTOMER_CANCEL_CONFIRMED',
  'CUSTOMER_CANCEL_FAILED',
  'SMS_SENT',
  'SMS_FAILED'
) NOT NULL;

