ALTER TABLE audit_logs 
MODIFY action VARCHAR(191) NOT NULL;

ALTER TABLE audit_logs 
MODIFY action ENUM(
  'UI_PHONE_ENTERED',
  'UI_NAME_ENTERED',
  'UI_CANCEL_ATTEMPT',
  'UI_FORM_ABANDONED',
  'UI_SETTINGS_SAVED',
  'APPOINTMENT_CREATE_ATTEMPT',
  'APPOINTMENT_CREATED',
  'APPOINTMENT_APPROVED',
  'APPOINTMENT_CANCELLED',
  'APPOINTMENT_CANCEL_ATTEMPT',
  'APPOINTMENT_CANCEL_BLOCKED_PAST',
  'APPOINTMENT_CANCEL_DENIED',
  'CUSTOMER_CANCEL_PHONE_ENTERED',
  'CUSTOMER_CANCEL_OTP_SENT',
  'CUSTOMER_CANCEL_CONFIRMED',
  'CUSTOMER_CANCEL_FAILED',
  'SETTINGS_CREATED',
  'SETTINGS_UPDATED',
  'LEDGER_CREATED',
  'LEDGER_UPDATED',
  'LEDGER_DELETED',
  'EXPENSE_CREATED',
  'EXPENSE_UPDATED',
  'EXPENSE_DELETED',
  'SMS_SENT',
  'SMS_FAILED',
  'WORKING_HOUR_UPDATED',
  'WORKING_HOUR_OVERRIDE_CREATED',
  'WORKING_HOUR_OVERRIDE_DELETED',
  'WORKING_HOUR_OVERRIDE_APPLIED',
  'APPOINTMENT_CANCELLED_BY_OVERRIDE',
  'SUBSCRIPTION_CREATED',
  'SUBSCRIPTION_UPDATED',
  'SUBSCRIPTION_CANCELLED',
  'SUBSCRIPTION_APPOINTMENTS_GENERATED'
) NOT NULL;

CREATE TABLE `subscriptions` (
    `id` VARCHAR(191) NOT NULL,
    `barberId` VARCHAR(191) NOT NULL,
    `customerName` VARCHAR(255) NOT NULL,
    `customerPhone` VARCHAR(20) NOT NULL,
    `recurrenceType` ENUM('weekly', 'biweekly', 'monthly') NOT NULL,
    `dayOfWeek` INT NOT NULL,
    `weekOfMonth` INT NULL,
    `startTime` VARCHAR(10) NOT NULL,
    `durationMinutes` INT NOT NULL,
    `startDate` VARCHAR(191) NOT NULL,
    `endDate` VARCHAR(191) NULL,
    `isActive` BOOLEAN NOT NULL DEFAULT true,
    `createdAt` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
    `updatedAt` DATETIME(0) NOT NULL,

    INDEX `subscriptions_barberId_idx`(`barberId`),
    INDEX `subscriptions_customerPhone_idx`(`customerPhone`),
    INDEX `subscriptions_isActive_idx`(`isActive`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

ALTER TABLE `subscriptions` ADD CONSTRAINT `subscriptions_barberId_fkey` FOREIGN KEY (`barberId`) REFERENCES `barbers`(`id`) ON DELETE CASCADE ON UPDATE CASCADE;

ALTER TABLE `appointment_requests` ADD COLUMN `subscriptionId` VARCHAR(191) NULL;

ALTER TABLE `appointment_requests` ADD CONSTRAINT `appointment_requests_subscriptionId_fkey` FOREIGN KEY (`subscriptionId`) REFERENCES `subscriptions`(`id`) ON DELETE SET NULL ON UPDATE CASCADE;

CREATE INDEX `appointment_requests_subscriptionId_idx` ON `appointment_requests`(`subscriptionId`);

