-- AlterEnum - Fix audit action enum to match schema (final)
ALTER TABLE `audit_logs` MODIFY COLUMN `action` ENUM('UI_PHONE_ENTERED', 'UI_NAME_ENTERED', 'UI_CANCEL_ATTEMPT', 'APPOINTMENT_CREATED', 'APPOINTMENT_APPROVED', 'APPOINTMENT_CANCELLED', 'APPOINTMENT_CANCEL_ATTEMPT', 'APPOINTMENT_CANCEL_BLOCKED_PAST', 'SMS_SENT', 'SMS_FAILED') NOT NULL;


