-- 1. AuditAction enum'unu geçici olarak VARCHAR yap
ALTER TABLE audit_logs 
MODIFY action VARCHAR(191) NOT NULL;

-- 2. WorkingHourOverride tablosunu oluştur
CREATE TABLE `working_hour_overrides` (
  `id` VARCHAR(191) NOT NULL,
  `barberId` VARCHAR(191) NOT NULL,
  `date` VARCHAR(191) NOT NULL,
  `startTime` VARCHAR(10) NOT NULL,
  `endTime` VARCHAR(10) NOT NULL,
  `reason` TEXT,
  `createdAt` DATETIME(0) NOT NULL DEFAULT CURRENT_TIMESTAMP(0),
  PRIMARY KEY (`id`),
  INDEX `working_hour_overrides_barberId_date_idx` (`barberId`, `date`),
  CONSTRAINT `working_hour_overrides_barberId_fkey` FOREIGN KEY (`barberId`) REFERENCES `barbers` (`id`) ON DELETE CASCADE ON UPDATE CASCADE
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- 3. AuditAction enum'una yeni değerleri ekle
ALTER TABLE audit_logs 
MODIFY action ENUM(
  'UI_PHONE_ENTERED',
  'UI_NAME_ENTERED',
  'UI_CANCEL_ATTEMPT',
  'UI_FORM_ABANDONED',
  'UI_SETTINGS_SAVED',
  'APPOINTMENT_CREATE_ATTEMPT',
  'APPOINTMENT_CREATED',
  'APPOINTMENT_APPROVED',
  'APPOINTMENT_CANCELLED',
  'APPOINTMENT_CANCEL_ATTEMPT',
  'APPOINTMENT_CANCEL_BLOCKED_PAST',
  'APPOINTMENT_CANCEL_DENIED',
  'CUSTOMER_CANCEL_PHONE_ENTERED',
  'CUSTOMER_CANCEL_OTP_SENT',
  'CUSTOMER_CANCEL_CONFIRMED',
  'CUSTOMER_CANCEL_FAILED',
  'SETTINGS_CREATED',
  'SETTINGS_UPDATED',
  'LEDGER_CREATED',
  'LEDGER_UPDATED',
  'LEDGER_DELETED',
  'EXPENSE_CREATED',
  'EXPENSE_UPDATED',
  'EXPENSE_DELETED',
  'SMS_SENT',
  'SMS_FAILED',
  'WORKING_HOUR_UPDATED',
  'WORKING_HOUR_OVERRIDE_CREATED',
  'WORKING_HOUR_OVERRIDE_DELETED'
) NOT NULL;

