-- AlterEnum
ALTER TABLE `audit_logs` MODIFY COLUMN `action` ENUM('APPOINTMENT_FORM_PHONE_ENTERED', 'APPOINTMENT_FORM_NAME_ENTERED', 'APPOINTMENT_FORM_ABANDONED', 'APPOINTMENT_CREATED', 'APPOINTMENT_APPROVED', 'APPOINTMENT_CANCELLED', 'APPOINTMENT_REJECTED', 'APPOINTMENT_CANCELLED_BY_CUSTOMER', 'APPOINTMENT_CANCEL_ATTEMPT', 'APPOINTMENT_CANCEL_BLOCKED_PAST', 'LEDGER_CREATED', 'LEDGER_UPDATED', 'LEDGER_DELETED', 'EXPENSE_CREATED', 'EXPENSE_UPDATED', 'EXPENSE_DELETED', 'SMS_SENT', 'SMS_FAILED', 'AUTH_LOGIN', 'AUTH_LOGIN_FAILED', 'AUTH_LOGOUT', 'UI_ACTION', 'UI_PHONE_ENTERED', 'UI_NAME_ENTERED', 'UI_CANCEL_ATTEMPT') NOT NULL;


