-- 1. ENUM kolonunu geçici STRING yap
ALTER TABLE audit_logs 
MODIFY action VARCHAR(191) NOT NULL;

-- 2. Eski enum'da olmayan değerleri geçici olarak SMS_SENT yap (güvenli değer)
UPDATE audit_logs 
SET action = 'SMS_SENT' 
WHERE action NOT IN (
  'UI_PHONE_ENTERED',
  'UI_NAME_ENTERED',
  'UI_CANCEL_ATTEMPT',
  'APPOINTMENT_CREATED',
  'APPOINTMENT_APPROVED',
  'APPOINTMENT_CANCELLED',
  'APPOINTMENT_CANCEL_ATTEMPT',
  'APPOINTMENT_CANCEL_BLOCKED_PAST',
  'CUSTOMER_CANCEL_PHONE_ENTERED',
  'CUSTOMER_CANCEL_OTP_SENT',
  'CUSTOMER_CANCEL_CONFIRMED',
  'CUSTOMER_CANCEL_FAILED',
  'SMS_SENT',
  'SMS_FAILED'
);

-- 3. AuditAction enum'unun TÜM güncel değerlerini ekle
ALTER TABLE audit_logs 
MODIFY action ENUM(
  'UI_PHONE_ENTERED',
  'UI_NAME_ENTERED',
  'UI_CANCEL_ATTEMPT',
  'APPOINTMENT_CREATED',
  'APPOINTMENT_APPROVED',
  'APPOINTMENT_CANCELLED',
  'APPOINTMENT_CANCEL_ATTEMPT',
  'APPOINTMENT_CANCEL_BLOCKED_PAST',
  'CUSTOMER_CANCEL_PHONE_ENTERED',
  'CUSTOMER_CANCEL_OTP_SENT',
  'CUSTOMER_CANCEL_CONFIRMED',
  'CUSTOMER_CANCEL_FAILED',
  'SMS_SENT',
  'SMS_FAILED'
) NOT NULL;
