-- AlterEnum
ALTER TABLE `audit_logs` MODIFY COLUMN `action` ENUM('APPOINTMENT_FORM_PHONE_ENTERED', 'APPOINTMENT_FORM_NAME_ENTERED', 'APPOINTMENT_FORM_ABANDONED', 'APPOINTMENT_CREATED', 'APPOINTMENT_APPROVED', 'APPOINTMENT_CANCELLED', 'APPOINTMENT_REJECTED', 'APPOINTMENT_CANCELLED_BY_CUSTOMER', 'CUSTOMER_CANCEL_PHONE_ENTERED', 'CUSTOMER_CANCEL_OTP_REQUESTED', 'CUSTOMER_CANCEL_OTP_FAILED', 'CUSTOMER_CANCEL_OTP_VERIFIED', 'LEDGER_CREATED', 'LEDGER_UPDATED', 'LEDGER_DELETED', 'EXPENSE_CREATED', 'EXPENSE_UPDATED', 'EXPENSE_DELETED', 'SMS_SENT', 'SMS_FAILED', 'AUTH_LOGIN', 'AUTH_LOGIN_FAILED', 'AUTH_LOGOUT', 'UI_ACTION') NOT NULL;


